### ISSUE TITLE
Unable to change default fact for certain tests

### ISSUE THREAD

**Issue by bastelfreak** [mcanevet/rspec-puppet-facts#38]
Hi, I need to mock the ipaddress and macaddress fact for two tests, here is my a part of my spec file:
```ruby
require 'spec_helper'

describe 'profiles::base', type: :class do
  on_supported_os.each do |os, facts|
    context "on #{os} " do
      let :facts do
        # mocked_facts(facts)
        facts
      end 

      context 'the default base profile on all systems' do
        it { should compile.with_all_deps }
        describe 'we create awesome facts' do
          let :facts do
            super().merge(
              ipaddress: '10.16.254.253',
              macaddress: 'AA:BB:CC:DD:EE:FF'
            )
          end
          it do
            should contain_file_line('set-ip').with(
              path: '/etc/facter/facts.d/sach.txt',
              line: 'primary_ip=10.16.254.253'
          )
          end
          it do
            should contain_file_line('set-mac').with(
              path: '/etc/facter/facts.d/sach.txt',
              line: 'primary_mac=AA:BB:CC:DD:EE:FF'
          )
          end
        end
      end
    end
  end
end
```

This results in:
```
  1) profiles::base on debian-6-x86_64  the default base profile on all systems we create awesome facts should contain File_line[set-ip] with path => "/etc/facter/facts.d/sach.txt" and line => "primary_ip=10.16.254.253"
     Failure/Error:
         should contain_file_line('set-ip').with(
           path: '/etc/facter/facts.d/sach.txt',
           line: 'primary_ip=10.16.254.253'
       )
     
       expected that the catalogue would contain File_line[set-ip] with line set to "primary_ip=10.16.254.253" but it is set to "primary_ip=10.0.2.15"
     # ./spec/classes/base_spec.rb:100:in `block (6 levels) in <top (required)>'

  2) profiles::base on debian-6-x86_64  the default base profile on all systems we create awesome facts should contain File_line[set-mac] with path => "/etc/facter/facts.d/sach.txt" and line => "primary_mac=AA:BB:CC:DD:EE:FF"
     Failure/Error:
         should contain_file_line('set-mac').with(
           path: '/etc/facter/facts.d/sach.txt',
           line: 'primary_mac=AA:BB:CC:DD:EE:FF'
       )
     
       expected that the catalogue would contain File_line[set-mac] with line set to "primary_mac=AA:BB:CC:DD:EE:FF" but it is set to "primary_mac=08:00:27:d9:42:67"
     # ./spec/classes/base_spec.rb:106:in `block (6 levels) in <top (required)>'
```

Instead of ` super().merge()` I also tried `facts.merge()`, which resulted in the same error.

**Comment by mcanevet** [comment]
@bastelfreak is this syntax supposed to work: `ipaddress: '10.16.254.253'`?
Shouldn't it be `ipaddress => '10.16.254.253'`

**Comment by mcanevet** [comment]
I close because I think it's a syntax error on your side. Feel free to reopen if it is not the case
