### ISSUE TITLE
PR #72 breaks Puppet 6

### ISSUE THREAD

**Issue by baurmatt** [mcanevet/rspec-puppet-facts#73]
The change done in #72 breaks our CI using Puppet 6:

```
An error occurred while loading ./spec/classes/vhosts_spec.rb.
Failure/Error:
  on_supported_os.each do |os, os_facts|
    context "on #{os}" do
      let(:facts) { os_facts }
      let :pre_condition do
        <<-EOF
        # Fake assert_private function from stdlib to not fail within this test
        function assert_private () { }
        include apache
        EOF
      end

LoadError:
  cannot load such file -- augeas
# /usr/local/bundle/gems/rspec-puppet-2.7.1/lib/rspec-puppet/monkey_patches.rb:350:in `require'
# /usr/local/bundle/gems/rspec-puppet-2.7.1/lib/rspec-puppet/monkey_patches.rb:350:in `require'
# /usr/local/bundle/gems/rspec-puppet-facts-1.9.1/lib/rspec-puppet-facts.rb:220:in `common_facts'
# /usr/local/bundle/gems/rspec-puppet-facts-1.9.1/lib/rspec-puppet-facts.rb:134:in `block in on_supported_os'
# /usr/local/bundle/gems/rspec-puppet-facts-1.9.1/lib/rspec-puppet-facts.rb:117:in `map'
# /usr/local/bundle/gems/rspec-puppet-facts-1.9.1/lib/rspec-puppet-facts.rb:117:in `on_supported_os'
# ./spec/classes/vhosts_spec.rb:4:in `block in <top (required)>'
# ./spec/classes/vhosts_spec.rb:3:in `<top (required)>'
```

That's probably because the rescue doesn't rescue a `LoadError`. I will submit a PR for this.

**Comment by baurmatt** [comment]
@mcanevet Could you please elaborate why the originally implemented version was good enough for Puppet 6? From my understanding, `if Puppet.features.augeas?` doesn't require Augeas to be present.

**Comment by baurmatt** [comment]
I see two options fixing this:

1. Change `rescue => e` to `rescue LoadError => e`
This still throws `Failed to retrieve Augeas version: cannot load such file -- augeas` warnings, which aren't really nice.

2. Revert 5156ec47a180fd059a3f1276a6ec170fbae5980a - it worked for us with with Puppet 6.0.0

**Comment by DavidS** [comment]
I see the same in https://travis-ci.org/puppetlabs/cisco_ios/jobs/445535959#L933-L942 :

```
An error occurred while loading ./spec/classes/proxy_spec.rb.
Failure/Error:
    on_supported_os(proxy_os).each do |os, os_facts|
      context "on #{os}" do
        let(:facts) { os_facts }
  
        it { is_expected.to compile }
      end
    end
LoadError:
  cannot load such file -- augeas
# ./vendor/bundle/ruby/2.4.0/gems/rspec-puppet-2.7.1/lib/rspec-puppet/monkey_patches.rb:350:in `require'
# ./vendor/bundle/ruby/2.4.0/gems/rspec-puppet-2.7.1/lib/rspec-puppet/monkey_patches.rb:350:in `require'
# ./vendor/bundle/ruby/2.4.0/gems/rspec-puppet-facts-1.9.1/lib/rspec-puppet-facts.rb:220:in `common_facts'
# ./vendor/bundle/ruby/2.4.0/gems/rspec-puppet-facts-1.9.1/lib/rspec-puppet-facts.rb:134:in `block in on_supported_os'
# ./vendor/bundle/ruby/2.4.0/gems/rspec-puppet-facts-1.9.1/lib/rspec-puppet-facts.rb:117:in `map'
# ./vendor/bundle/ruby/2.4.0/gems/rspec-puppet-facts-1.9.1/lib/rspec-puppet-facts.rb:117:in `on_supported_os'
# ./spec/classes/proxy_spec.rb:4:in `block in <top (required)>'
# ./spec/classes/proxy_spec.rb:3:in `<top (required)>'
```

**Comment by DavidS** [comment]
@baurmatt the issue seems to be that `Puppet.features.augeas?`  now always returns `false`, even if augeas is present in the bundle. You first option, rescuing the `LoadError` seems to be the way to go then.

**Comment by baurmatt** [comment]
Alright then, opened up #74 for the fix.
